;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	comment-dwim
	crux-move-beginning-of-line
	crux-smart-kill-line
	electric-newline-and-maybe-indent
	evil-backward-char
	evil-change
	evil-copy-from-above
	evil-delete
	evil-delete-backward-char-and-join
	evil-delete-char
	evil-force-normal-state
	evil-forward-char
	evil-inner-word
	evil-insert
	evil-insert-state
	evil-next-line
	evil-normal-state
	evil-paste-last-insertion
	evil-previous-line
	evil-shift-left-line
	forward-to-word
	handle-switch-frame
	ignore-preserving-kill-region
	lsp-ui-doc--handle-mouse-movement
	mouse-set-region
	save-some-buffers
	wdired--self-insert
	))

(setq mc/cmds-to-run-once
      '(
	compile
	crux-duplicate-current-line-or-region
	find-file
	mc--insert-letter-and-increase
	mc--insert-number-and-increase
	))
