;;   -*- lexical-binding: t; -*-
;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	crux-smart-kill-line
	evil-backward-char
	evil-change
	evil-delete
	evil-forward-char
	evil-inner-word
	evil-insert
	evil-next-line
	evil-normal-state
	evil-previous-line
	wdired--self-insert
	))

(setq mc/cmds-to-run-once
      '(
	))
